name: Pull request build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:

  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Push Code
        run: |
          ls
          echo $GITHUB_EVENT_PATH
          echo $GITHUB_REF
          echo github.event.number = ${{ github.event.number  }}
          echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
          echo github.event.issue.number = ${{ github.event.issue.number }}
