name: Pull request build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:

  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Push Code
        run: |
          ls
          echo "Github Ref:" $GITHUB_REF
          echo "Github PR" ${{ github.event.pull_request.number }}
