name: Pull request build

on:
  workflow_dispatch:
  pull_request:
    branches:
    - master
    types:
      - opened
      - synchronize

jobs:

  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: set up git
        run: git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

      - name: Install Dependencies
        run: npm ci

      - name: Push Code
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete --exclude=".git"
          remote_path: /root/pr012/
          remote_host: test.decentraland.vote
          remote_user: root
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy Code
        uses: garygrossgarten/github-action-ssh@release
        with:
          username: root
          host: test.decentraland.vote
          privateKey: ${{ secrets.DEPLOY_KEY }}
          command: ./deploy.sh pr012

