name: Pull request build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:

  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Push Code
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          remote_path: /root/pr011/
          remote_host: test.decentraland.vote
          remote_user: root
          remote_key: ${{ secrets.DEPLOY_KEY }}

